import { useMemo, useState } from 'react';
import { Aperture, ArrowDownLeft, ArrowLeft, ArrowUpRight, Check, ChevronDown, CircleHelp, Clock3, ExternalLink, FileImage, Heart, Info, Instagram, LockKeyhole, MessageCircle, MoreHorizontal, Plus, Search, Send, Settings2, ShieldCheck, Sparkles, Sun, Trash2, X } from 'lucide-react';
import { conversationFixtures, safeInstagramUrl, type Conversation, type DemoMessage, type Route } from './domain';

const nav:[Route,string,typeof MessageCircle][]=[['inbox','Inbox',MessageCircle],['updates','My updates',Aperture],['create','Create',Plus],['settings','Settings',Settings2]];
function Avatar({person,size='normal'}:{person:Conversation;size?:'normal'|'small'}){return <span className={`avatar ${person.color} ${size}`} aria-hidden="true">{person.initials}</span>}
function Brand(){return <div className="brand"><span className="brand-mark"><Heart size={17} strokeWidth={2.3}/></span><span>offline<span className="brand-light">social</span></span></div>}
function App(){
 const [page,setPage]=useState<Route>('inbox'); const [selectedId,setSelectedId]=useState('c1'); const [query,setQuery]=useState(''); const [message,setMessage]=useState(''); const [sent,setSent]=useState<Record<string,DemoMessage[]>>({}); const [toast,setToast]=useState(''); const [showLimits,setShowLimits]=useState(false); const [connected,setConnected]=useState(false); const [consent,setConsent]=useState(false); const [earlier,setEarlier]=useState(false); const [mobileList,setMobileList]=useState(true); const [limit,setLimit]=useState('5'); const [reduced,setReduced]=useState(false); const [draft,setDraft]=useState(''); const [fileName,setFileName]=useState(''); const [publishPreview,setPublishPreview]=useState(false);
 const conversations=useMemo(()=>conversationFixtures.filter(c=>(c.name+c.handle+c.preview).toLowerCase().includes(query.toLowerCase())),[query]);
 const selected=conversationFixtures.find(c=>c.id===selectedId)!; const allMessages=[...selected.messages,...(sent[selected.id]||[])]; const messages=earlier?allMessages:allMessages.slice(-Number(limit)); const hasEarlier=messages.length<allMessages.length;
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),3000)};
 const openConversation=(id:string)=>{setSelectedId(id);setMobileList(false)};
 const submitMessage=(e:React.FormEvent)=>{e.preventDefault();if(!message.trim())return;const next={id:`local-${Date.now()}`,from:'you' as const,kind:'text' as const,text:message.trim(),time:'Now'};setSent(v=>({...v,[selected.id]:[...(v[selected.id]||[]),next]}));setMessage('');notify('Demo message added locally. Nothing was sent to Instagram.');};
 const finishPublish=()=>{setPublishPreview(false);setDraft('');setFileName('');notify('Demo only: no content was published to Instagram.');};
 const clearLocal=()=>{setSent({});setQuery('');setMessage('');setDraft('');setFileName('');setConnected(false);notify('Local demo data cleared.');};
 const navTo=(next:Route)=>{setPage(next);setMobileList(true)};
 return <div className={`app-shell ${reduced?'reduced':''}`}>
  <aside className="rail"><div className="rail-top"><Brand/><span className="brand-caption">A quieter corner of Instagram</span></div>
   <div className="workspace-label">YOUR SPACE <ChevronDown size={13}/></div>
   <nav className="main-nav" aria-label="Main navigation">{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${page===id?'active':''}`} onClick={()=>navTo(id)}><Icon size={18}/><span>{label}</span>{id==='inbox'&&<span className="nav-count">2</span>}</button>)}</nav>
   <div className="rail-bottom"><div className="limit-card"><div className="limit-icon"><Clock3 size={17}/></div><div><strong>Your time, your terms</strong><span>{limit} items per check-in</span></div><button className="icon-btn subtle" aria-label="Change check-in limit" onClick={()=>setShowLimits(true)}><MoreHorizontal size={18}/></button><div className="limit-track"><span style={{width:'28%'}}/></div><small>Room to breathe, by design</small></div>
    <button className="profile-link" onClick={()=>navTo('settings')}><span className="self-avatar">Y</span><span className="profile-text"><strong>Your space</strong><small>{connected?'Demo connection':'Not connected'}</small></span><MoreHorizontal size={18}/></button>
   </div>
  </aside>
  <main className="main-area">
   <header className="topbar"><button className="mobile-brand" onClick={()=>navTo('inbox')}><Brand/></button><div className="crumb"><span>YOUR SPACE</span><b>/</b><strong>{page==='inbox'?'Inbox':page==='updates'?'My updates':page==='create'?'Create':page==='settings'?'Settings':'Capabilities'}</strong></div><div className="top-actions"><span className="demo-pill"><span/> DEMO MODE</span><button className="top-help" onClick={()=>navTo('capabilities')} aria-label="Capabilities and limitations"><CircleHelp size={18}/></button></div></header>
   {page==='inbox'&&<section className={`inbox-view ${!mobileList?'conversation-open':''}`}>
    <div className="inbox-list"><div className="section-heading"><div><div className="eyebrow">A LITTLE CATCH-UP</div><h1>Your inbox<span className="dot">.</span></h1><p>Good conversations, with room to pause.</p></div><button className="round-button" aria-label="New message" onClick={()=>notify('Starting new Instagram conversations is unavailable in demo mode.')}><Plus size={18}/></button></div>
     <div className="inbox-filter"><button className="filter-active">All <span>3</span></button><button onClick={()=>notify('Unread filtering is not connected in demo mode.')}>Unread <span className="filter-dot"/></button><button className="filter-icon" aria-label="Inbox options"><MoreHorizontal size={18}/></button></div>
     <label className="search-box"><Search size={16}/><input aria-label="Search demo conversations" placeholder="Find a conversation" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label>
     <div className="list-label">RECENT <span>{conversations.length} conversations</span></div>
     <div className="conversation-items">{conversations.length?conversations.map(c=><button key={c.id} className={`conversation-row ${selectedId===c.id?'selected':''}`} onClick={()=>openConversation(c.id)}><span className="avatar-wrap"><Avatar person={c}/>{c.unread&&<i className="unread-dot"/>}</span><span className="row-copy"><span className="row-top"><strong>{c.name}</strong><time>{c.when}</time></span><span className="row-bottom"><span>{c.preview}</span>{c.unread&&<i className="message-unread"/>}</span></span></button>):<div className="no-results"><Search size={19}/><strong>No conversations found</strong><span>Try another name.</span></div>}</div>
     <div className="list-foot"><span className="foot-spark"><Sparkles size={14}/></span><span>That’s everyone for now.<br/><strong>No feed to fall into.</strong></span></div>
    </div>
    <div className="thread-pane"><div className="thread-head"><button className="back-button" onClick={()=>setMobileList(true)} aria-label="Back to inbox"><ArrowLeft size={19}/></button><Avatar person={selected} size="small"/><div className="thread-person"><strong>{selected.name}</strong><span>{selected.handle} <i/> Available for messages</span></div><button className="thread-options" aria-label="Conversation options"><MoreHorizontal size={20}/></button></div>
     <div className="thread-note"><ShieldCheck size={14}/><span>Demo conversation · messages are sample data and stay on this device.</span></div>
      <div className="messages-scroll" role="log" aria-label={`Conversation with ${selected.name}`} aria-live="polite">{earlier&&!hasEarlier&&<div className="older-note">You’re at the beginning of this demo conversation.</div>}{hasEarlier&&!earlier&&<button className="load-earlier" onClick={()=>setEarlier(true)}><ArrowDownLeft size={13}/> Load earlier messages</button>}
      <div className="day-divider"><span/>TODAY<span/></div>
      {messages.map(m=><MessageBubble key={m.id} item={m} person={selected}/>)}
      <span className="read-receipt"><Check size={12}/> Seen</span>
      <div className="end-of-thread"><span/>You’re all caught up<span/></div>
     </div>
     <form className="composer" onSubmit={submitMessage}><div className="composer-tools"><button type="button" className="composer-tool" aria-label="Attach photo" onClick={()=>notify('Attachments are unavailable in this demo.')}><Plus size={18}/></button><button type="button" className="composer-tool" aria-label="Choose a reaction" onClick={()=>setMessage(v=>v+' 💛')}><Heart size={17}/></button></div><input aria-label="Message" placeholder="Write a thoughtful reply…" value={message} onChange={e=>setMessage(e.target.value)} /><button className="send-button" type="submit" disabled={!message.trim()} aria-label="Send demo message"><Send size={16}/></button><div className="compose-foot">Your conversations can wait. No read receipts here.</div></form>
    </div>
   </section>}
   {page==='updates'&&<section className="page-content"><div className="eyebrow">INTENTIONAL, NOT INFINITE</div><h1>My updates<span className="dot">.</span></h1><p className="page-lede">A small window into what you’ve shared. Your friends’ home feed isn’t available through Instagram’s official APIs.</p><div className="feature-banner"><div className="banner-icon"><Aperture size={22}/></div><div><strong>Your account isn’t connected</strong><span>Connect a supported professional account to see your own accessible profile media.</span></div><button className="text-action" onClick={()=>{navTo('settings');setTimeout(()=>document.getElementById('connect-card')?.scrollIntoView({behavior:'smooth'}),0)}}>Learn about connecting <ArrowUpRight size={15}/></button></div><div className="quiet-card"><div className="quiet-art"><div className="sun-circle"><Sun size={31}/></div><span className="art-orbit orbit-one"/><span className="art-orbit orbit-two"/><span className="art-stem"/><span className="art-leaf leaf-one"/><span className="art-leaf leaf-two"/></div><div className="eyebrow">A NOTE ON YOUR FEED</div><h2>Some things are better<br/>left out of the scroll.</h2><p>The official Instagram API doesn’t provide your followed-accounts home feed, other people’s general Stories, or a Reels discovery feed. This app won’t imitate one.</p><button className="button-secondary" onClick={()=>navTo('capabilities')}>See what is supported <ArrowUpRight size={15}/></button></div></section>}
   {page==='create'&&<section className="page-content create-page"><div className="eyebrow">SHARE WITH INTENTION</div><h1>Create something<span className="dot">.</span></h1><p className="page-lede">Draft a post for yourself. Publishing is unavailable until a supported account and Meta approval are configured.</p><div className="create-grid"><div className="create-form-card"><div className="card-title"><div><strong>Your next post</strong><span>Nothing leaves this page until you confirm.</span></div><span className="local-only"><LockKeyhole size={12}/> LOCAL ONLY</span></div><div className="content-types" role="group" aria-label="Content type"><button className="type-selected"><FileImage size={16}/> Photo post <Check size={14}/></button><button onClick={()=>notify('Reel publishing is disabled until live eligibility is verified.')}><span className="type-play">▶</span> Reel <Info size={14}/></button><button onClick={()=>notify('Story publishing is disabled until live eligibility is verified.')}><Aperture size={15}/> Story <Info size={14}/></button></div><label className="upload-zone"><input type="file" accept="image/*" onChange={e=>setFileName(e.target.files?.[0]?.name||'')}/><span className="upload-icon"><Plus size={20}/></span><strong>{fileName||'Choose a photo to preview'}</strong><span>Image preview stays on this device.</span><small>JPG, PNG or WebP · demo only</small></label><label className="caption-label">CAPTION <span>Optional</span><textarea placeholder="Add a few words…" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2200}/></label><div className="publish-explainer"><Info size={16}/><span>Instagram publishing isn’t connected. This draft is local and will not be uploaded.</span></div><button className="button-primary publish-button" disabled={!fileName} onClick={()=>setPublishPreview(true)}>Review draft <ArrowUpRight size={15}/></button></div><div className="create-side-note"><span className="note-icon"><Sparkles size={17}/></span><div className="eyebrow">A GENTLE REMINDER</div><h3>Share it, then<br/>come back to life.</h3><p>No scheduling queues, engagement tricks, or prompts to keep posting. Just a quiet place to prepare something you’d like to share.</p><button className="plain-link" onClick={()=>navTo('capabilities')}>Publishing limitations <ArrowUpRight size={14}/></button></div></div></section>}
   {page==='settings'&&<section className="page-content settings-page"><div className="eyebrow">YOUR SPACE, YOUR RULES</div><h1>Settings<span className="dot">.</span></h1><p className="page-lede">A few thoughtful defaults, always yours to change.</p><div className="settings-layout"><div className="settings-main"><div className="settings-card" id="connect-card"><div className="settings-card-head"><span className="settings-symbol"><Instagram size={19}/></span><div><strong>Instagram connection</strong><span>{connected?'Demo mode only':'No account connected'}</span></div><span className={`status-pill ${connected?'status-demo':''}`}><i/>{connected?'DEMO':'NOT CONNECTED'}</span></div><div className="settings-card-body"><p>Instagram login happens on Meta’s website. This demo does not connect to Instagram or receive credentials.</p><div className="account-note"><ShieldCheck size={17}/><span>Only professional Creator and Business accounts are supported by the official API. Personal accounts can’t connect.</span></div><label className="consent-row"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I understand the account eligibility and API limitations.</span></label><button className="button-primary connect-button" disabled={!consent} onClick={()=>{setConnected(true);notify('Demo mode enabled. No Instagram account was connected.')}}><Instagram size={16}/> {connected?'Demo mode is active':'Try demo mode'} <ArrowUpRight size={14}/></button><div className="connection-foot"><LockKeyhole size={13}/> No passwords requested · No Meta OAuth configured</div></div></div>
      <div className="settings-card"><div className="settings-card-head"><span className="settings-symbol warm"><Clock3 size={19}/></span><div><strong>Check-in boundaries</strong><span>Keep each visit deliberate</span></div></div><div className="settings-card-body"><div className="setting-row"><div><strong>Conversation preview</strong><span>Load this many messages initially</span></div><select value={limit} onChange={e=>setLimit(e.target.value)} aria-label="Initial conversation preview"><option value="5">5 messages</option><option value="10">10 messages</option><option value="15">15 messages</option></select></div><p className="setting-hint">Earlier messages always require a deliberate tap. No content loads automatically.</p><div className="setting-row"><div><strong>Video autoplay</strong><span>Always off; playback requires a deliberate action</span></div><button className="toggle" aria-label="Video autoplay is always off" aria-pressed="false" disabled><span/></button></div></div></div>
      <div className="settings-card"><div className="settings-card-head"><span className="settings-symbol lavender"><Sparkles size={18}/></span><div><strong>Comfort & access</strong><span>Make this space feel right</span></div></div><div className="settings-card-body"><div className="setting-row"><div><strong>Reduced motion</strong><span>Keep transitions gentle</span></div><button className={`toggle ${reduced?'on':''}`} aria-label="Reduced motion" aria-pressed={reduced} onClick={()=>setReduced(v=>!v)}><span/></button></div></div></div>
     </div><aside className="settings-aside"><div className="privacy-card"><ShieldCheck size={19}/><strong>Your data stays yours.</strong><p>Demo conversations are sample data. Replies are stored only in this browser session and disappear on refresh.</p><button onClick={()=>navTo('capabilities')}>Privacy & capabilities <ArrowUpRight size={14}/></button></div><div className="danger-card"><div><strong>Clear local app data</strong><span>Remove this session’s demo replies.</span></div><button className="clear-button" onClick={clearLocal}><Trash2 size={15}/> Clear</button></div></aside></div></section>}
   {page==='capabilities'&&<section className="page-content capability-page"><div className="eyebrow">PLAIN SPEAKING, BY DESIGN</div><h1>What this can do<span className="dot">.</span></h1><p className="page-lede">Before you connect anything, here’s what Instagram’s official APIs allow—and where they stop.</p><div className="notice-strip"><Info size={18}/><span>This is a demo. No account is connected, no Instagram data is loaded, and no messages or posts are sent.</span></div><div className="capability-grid"><Capability status="LIMITED" title="Instagram accounts" body="Official Instagram Login is for professional Creator and Business accounts. Ordinary personal accounts aren’t supported. This login model does not require a linked Facebook Page."/><Capability status="UNAVAILABLE" title="Your home feed" body="The API does not provide a general feed of posts from accounts you follow. We won’t recreate or simulate one."/><Capability status="UNAVAILABLE" title="Stories & Reels discovery" body="There’s no general viewer for other people’s Stories or Reels, and no way for this app to remove Instagram’s own Reels tab."/><Capability status="CONDITIONAL" title="Inbox & shared Reels" body="Professional accounts may access eligible messaging conversations with permission and review. Shared media may arrive as only an image/video URL; every Reel is not guaranteed playable here."/><Capability status="CONDITIONAL" title="Publishing" body="Eligible professional accounts can publish certain documented media formats with the right permission. Stories and Reels have format and account restrictions. This demo is not connected."/><Capability status="UNAVAILABLE" title="Friends’ updates" body="The app cannot browse arbitrary accounts’ posts or Stories. It can only show account-owned media the authorized API returns."/></div><div className="capability-footer"><span><ShieldCheck size={16}/> No scraping. No password collection. No private endpoints.</span><button onClick={()=>navTo('settings')}>Account settings <ArrowUpRight size={14}/></button></div></section>}
   <footer className="app-footer"><span>Made for people, not the feed.</span><button onClick={()=>navTo('capabilities')}>Capabilities & privacy</button><span className="footer-version">OFFLINE SOCIAL · DEMO</span></footer>
  </main>
  <nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>navTo(id)} aria-current={page===id?'page':undefined}><Icon size={19}/><span>{label}</span></button>)}</nav>
  {showLimits&&<div className="modal-scrim" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setShowLimits(false)}><section className="limit-modal" role="dialog" aria-modal="true" aria-labelledby="limit-title"><button className="modal-close" onClick={()=>setShowLimits(false)} aria-label="Close"><X size={17}/></button><span className="modal-icon"><Clock3 size={21}/></span><div className="eyebrow">A SMALL BOUNDARY</div><h2 id="limit-title">How much feels like enough?</h2><p>There’s no endless list here. Choose a modest message preview and load older messages only when you ask.</p><div className="limit-options">{['5','10','15'].map(n=><button className={limit===n?'selected':''} key={n} onClick={()=>setLimit(n)}><strong>{n}</strong><span>messages</span>{limit===n&&<Check size={14}/>}</button>)}</div><button className="button-primary modal-done" onClick={()=>setShowLimits(false)}>That feels right</button></section></div>}
  {publishPreview&&<div className="modal-scrim"><section className="limit-modal publish-modal" role="dialog" aria-modal="true" aria-labelledby="publish-title"><button className="modal-close" onClick={()=>setPublishPreview(false)} aria-label="Close"><X size={17}/></button><span className="modal-icon"><FileImage size={21}/></span><div className="eyebrow">LOCAL DRAFT ONLY</div><h2 id="publish-title">Ready to share?</h2><p>This would be a photo post to Instagram. No Instagram account is connected, so nothing can be published.</p><div className="draft-preview"><strong>{fileName}</strong><span>{draft||'No caption added.'}</span></div><button className="button-primary modal-done" onClick={finishPublish}>Done</button><button className="plain-link cancel-draft" onClick={()=>setPublishPreview(false)}>Keep editing</button></section></div>}
  {toast&&<div className="toast" role="status"><Info size={16}/>{toast}</div>}
 </div>
}
function MessageBubble({item,person}:{item:DemoMessage;person:Conversation}){const isYou=item.from==='you';const link=item.kind==='link'&&item.url?safeInstagramUrl(item.url):null;return <div className={`message-line ${isYou?'mine':''}`}>{!isYou&&<Avatar person={person} size="small"/>}<div className="message-block"><div className={`bubble ${isYou?'outgoing':''}`}>{item.kind==='link'?<div className="shared-link"><div className="shared-top"><span className="shared-ig"><Instagram size={14}/></span><span><strong>Shared on Instagram</strong><small>URL preview only · not playable here</small></span></div><div className="reel-preview"><span className="reel-play">▶</span><span>Shared Reel</span></div>{link?<a href={link} target="_blank" rel="noreferrer">Open in Instagram <ExternalLink size={12}/></a>:<span className="unavailable-link">Link not provided by API</span>}</div>:item.text}</div><span className="message-time">{item.time}</span></div></div>}
function Capability({status,title,body}:{status:string;title:string;body:string}){return <article className="capability-card"><div className={`cap-status ${status.toLowerCase()}`}><span/> {status}</div><h2>{title}</h2><p>{body}</p></article>}
export default App;
